### ISSUE TITLE
Config menu and file not working

### ISSUE THREAD

**Issue by Harry126172** [Karashok-Leo/L2Hostility-Fabricated#2]
Hello, I've been trying to turn off the custom nameplates in the config and it doesnt change anything in game no matter what values I set, am I missing a library or config API mod or something? I thought I had everything I needed but I'm not sure

**Comment by Karashok-Leo** [comment]
I guess I have fixed this issue in 1.1.4.
Feel free to re-open this issue if it still doesn't work.
